/**
 * useAppUpdate — discover whether a newer version is deployed.
 *
 * The OLD app shell (the version currently running) can't know the NEW
 * version's identity from its own baked-in APP_VERSION. So we fetch a tiny
 * static file (`/version.json`) at runtime — always over the network,
 * never from the workbox precache — and compare it to APP_VERSION.
 *
 * `version.json` is regenerated by `scripts/generate-version-json.mjs`
 * (wired as `prebuild` and `predev` in package.json) from the latest
 * CHANGELOG.md entry. The OLD shell's SW will see a byte-different sw.js
 * after a deploy; that triggers `$pwa.needRefresh` (handled in
 * PwaUpdatePrompt). This composable supplies the version metadata.
 */
import { APP_VERSION } from './useAppVersion'

export interface VersionInfo {
  version: string
  date: string
  bullets: string[]
}

export function useAppUpdate() {
  const availableUpdate = useState<VersionInfo | null>('app:available-update', () => null)
  const isLoading = useState<boolean>('app:update-loading', () => false)
  const error = useState<string | null>('app:update-error', () => null)
  const lastChecked = useState<number | null>('app:update-last-checked', () => null)

  /**
   * Fetch /version.json and set availableUpdate if it differs from
   * APP_VERSION. No-op if we're already on the latest.
   */
  async function fetchUpdate(): Promise<void> {
    if (isLoading.value) return
    isLoading.value = true
    error.value = null
    try {
      const res = await $fetch<VersionInfo>('/version.json', {
        // Always hit the network — never serve a stale precached copy.
        cache: 'no-store',
        headers: { 'Cache-Control': 'no-cache', 'Pragma': 'no-cache' },
      })
      if (res && typeof res.version === 'string' && res.version !== APP_VERSION) {
        availableUpdate.value = res
      } else {
        availableUpdate.value = null
      }
      lastChecked.value = Date.now()
    } catch (e) {
      error.value = e instanceof Error ? e.message : 'Failed to check for updates'
      availableUpdate.value = null
    } finally {
      isLoading.value = false
    }
  }

  /**
   * Clear the available-update state — call after the user dismisses the
   * toast or after they refresh.
   */
  function clearAvailableUpdate(): void {
    availableUpdate.value = null
  }

  return {
    availableUpdate: readonly(availableUpdate),
    isLoading: readonly(isLoading),
    error: readonly(error),
    lastChecked: readonly(lastChecked),
    fetchUpdate,
    clearAvailableUpdate,
  }
}
